name: skillswedstrijd
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/media/images/
    - assets/media/images/highlights/
    - assets/concerts.json
fonts:
  - family: Manier
    fonts:
      - asset: assets/fonts/manier-font-family/Manier-Medium.otf
        weight: 600
  - family:  Manrope
    fonts:
      - assets/fonts/Manrope/static/